pipeline {
  agent {label'Master11'}
  environment {
    IMAGE = "fndocker/moqui-vi-rest:latest"
  }
  stages {
    stage('Prepare') {
        steps {
           sh "cp -rf docker/* ./"
        }
    }
    stage('Source') {
      steps {
        dir('moqui') {
            git branch: 'master', credentialsId: 'loind', url: 'git@github.com:moqui/moqui-framework.git'
            withDockerContainer("openjdk:11-jdk") {
                sh "./gradlew getRuntime"
                sh "./gradlew getComponent -Pcomponent=PopCommerce"
            }
        }
       dir('moqui/runtime/component/moqui_vi_VN') {
            git branch: 'main', credentialsId: 'loind', url: 'git@github.com:olbius/moqui_vi_VN.git'
        }
        dir('moqui') {
             withDockerContainer("openjdk:11-jdk") {
                sh "./gradlew getDepends"
            }
        }
      }
    }
    stage('Build') {
      steps {
          dir('moqui') {
            withDockerContainer("openjdk:11-jdk") {
                sh "./gradlew clean build"
            }
          }

      }
    }
    stage('Docker') {
      steps {
        sh "docker build -t ${env.IMAGE} ."
        sh "docker push ${env.IMAGE}"
        sh "docker rmi ${env.IMAGE}"
      }
    }

    stage('Deploy') {
      steps {
        sh '''
            kubectl -n moqui-test  rollout restart deploy test-stest
        '''
      }
    }
  }
}
